# Generated by Django 5.0.6 on 2024-06-11 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_bonus_balance', models.IntegerField(blank=True, null=True, verbose_name=' Текущий баланс бонусных баллов')),
                ('loyalty_personal_proposal', models.CharField(verbose_name='Персональные предложения')),
                ('loyalty_QR_code', models.ImageField(upload_to='', verbose_name='QR-код')),
                ('loyalty_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=150, null=True, verbose_name='Номер заказа')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('order_shipment_date', models.DateTimeField(null=True, verbose_name='Дата доставки')),
                ('order_status', models.CharField(choices=[('1', 'Создан'), ('2', 'Выезд замерщика'), ('3', 'Подготовка эскиза'), ('4', 'Монтаж'), ('5', 'Выполнен'), ('6', 'Отклонен')], default='1', max_length=1, verbose_name='Статус заказа')),
                ('order_delivery_address', models.CharField(max_length=150, null=True, verbose_name='Адрес доставки')),
                ('order_contract', models.CharField(max_length=150, verbose_name='Договор')),
                ('order_price', models.FloatField(verbose_name='Стоимость заказа')),
                ('order_sketch1', models.ImageField(default='default_mebel.jpg', upload_to='', verbose_name='Эскиз1')),
                ('order_sketch2', models.ImageField(default='default_mebel.jpg', upload_to='', verbose_name='Эскиз2')),
                ('order_sketch3', models.ImageField(default='default_mebel.jpg', upload_to='', verbose_name='Эскиз3')),
                ('order_sketch4', models.ImageField(default='default_mebel.jpg', upload_to='', verbose_name='Эскиз4')),
                ('order_3D_model', models.ImageField(default='default_mebel.jpg', upload_to='', verbose_name='3D модель')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
