# Generated by Django 5.0.6 on 2024-06-21 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('1', 'Кухня'), ('2', 'Гардероб'), ('3', 'Прихожая'), ('4', 'Комод'), ('5', 'Стеллаж'), ('6', 'Комплексный заказ')], default=None, max_length=1, null=True, verbose_name='Тип мебели')),
                ('form', models.CharField(blank=True, choices=[('1', 'Прямая'), ('2', 'П-образная'), ('3', 'Угловая'), ('4', 'Г-образная')], default=None, max_length=1, null=True, verbose_name='Форма мебели')),
                ('addition', models.CharField(blank=True, choices=[('1', 'Барная стойка'), ('2', 'Остров'), ('3', 'Без дополнений')], default=None, max_length=1, null=True, verbose_name='Дополнения')),
                ('facades_material', models.CharField(blank=True, choices=[('1', 'ЛДСП'), ('2', 'Пленка ПВХ'), ('3', 'Пластик AGT'), ('4', 'Пластик Fenix'), ('5', 'Эмаль')], default=None, max_length=1, null=True, verbose_name='Материал фасада')),
                ('table_material', models.CharField(blank=True, choices=[('1', 'Столешница компакт-ламинат'), ('2', 'Кварцевая столешница'), ('3', 'Столешница ЛДСП с покрытием HPL'), ('4', 'Акриловая столешница')], default=None, max_length=1, null=True, verbose_name='Материал столешницы')),
                ('plumb', models.CharField(blank=True, choices=[('1', 'Необходим подбор сантехники'), ('2', 'Подбор сантехники не нужен')], default=None, max_length=1, null=True, verbose_name='Кухонная сантехника')),
                ('appliances', models.CharField(blank=True, choices=[('1', 'Необходим подбор техники'), ('2', 'Подбор техники не нужен')], default=None, max_length=1, null=True, verbose_name='Бытовая техника')),
                ('budget', models.CharField(blank=True, choices=[('1', 'до 300 000 ₽'), ('2', 'от 300 000 ₽ до 500 000 ₽'), ('3', 'от 500 000 ₽ до 700 000 ₽'), ('4', 'от 700 000 ₽')], default=None, max_length=1, null=True, verbose_name='Бюджет проекта')),
                ('consultation', models.CharField(blank=True, choices=[('1', 'Консультация нужна'), ('2', 'Консультация не нужна')], default=None, max_length=1, null=True, verbose_name='Консультация с экспертом по обустройству дома')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Телефон должен быть указан в формате: '+7ХХХХХХХХХХ'. Максимум 12 символов.", regex='^\\+?1?\\d{9,12}$')], verbose_name='Ваш номер телефона')),
                ('connection', models.CharField(choices=[('1', 'Звонок'), ('2', 'Telegram'), ('3', 'ВКонтакте')], default=None, max_length=1, verbose_name='Как с Вами связаться?')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ваша ссылка на Telegram/ВКонтакте')),
                ('data', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата')),
                ('time', models.CharField(blank=True, max_length=30, null=True, verbose_name='Время')),
            ],
        ),
        migrations.CreateModel(
            name='Finished_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('1', 'Гардероб'), ('2', 'Детская'), ('3', 'Комод'), ('4', 'Кухня'), ('5', 'Прихожая')], default='1', max_length=1, verbose_name='Тип мебели')),
                ('form', models.CharField(choices=[('1', 'Прямая'), ('2', 'Г-образная'), ('3', 'П-образная'), ('4', 'С барной стойкой'), ('5', 'С островом')], default='1', max_length=1, verbose_name='Форма мебели')),
                ('body_material', models.CharField(choices=[('1', 'ЛДСП'), ('2', 'МДФ'), ('3', 'Пленка ПВХ'), ('4', 'Пластик AGT'), ('5', 'Пластик Fenix'), ('6', 'Эмаль')], default='1', max_length=1, verbose_name='Материал корпуса')),
                ('facades_material', models.CharField(choices=[('1', 'ЛДСП'), ('2', 'МДФ'), ('3', 'Пленка ПВХ'), ('4', 'Пластик AGT'), ('5', 'Пластик Fenix'), ('6', 'Эмаль')], default='1', max_length=1, verbose_name='Материал фасадов')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 4')),
            ],
        ),
        migrations.CreateModel(
            name='Loyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_bonus_balance', models.IntegerField(blank=True, null=True, verbose_name=' Текущий баланс бонусных баллов')),
                ('loyalty_personal_proposal', models.CharField(max_length=200, verbose_name='Персональные предложения')),
                ('loyalty_QR_code', models.ImageField(upload_to='', verbose_name='QR-код')),
                ('loyalty_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=150, null=True, verbose_name='Номер заказа')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('order_shipment_date', models.DateTimeField(null=True, verbose_name='Дата доставки')),
                ('order_status', models.CharField(choices=[('1', 'Создан'), ('2', 'Выезд замерщика'), ('3', 'Подготовка эскиза'), ('4', 'Монтаж'), ('5', 'Выполнен'), ('6', 'Отклонен')], default='1', max_length=1, verbose_name='Статус заказа')),
                ('order_delivery_address', models.CharField(max_length=150, null=True, verbose_name='Адрес доставки')),
                ('order_contract', models.CharField(max_length=150, verbose_name='Договор')),
                ('order_price', models.FloatField(verbose_name='Стоимость заказа')),
                ('order_sketch1', models.ImageField(default='default_mebel.jpg', upload_to='', verbose_name='Эскиз1')),
                ('order_sketch2', models.ImageField(default='default_mebel.jpg', upload_to='', verbose_name='Эскиз2')),
                ('order_sketch3', models.ImageField(default='default_mebel.jpg', upload_to='', verbose_name='Эскиз3')),
                ('order_sketch4', models.ImageField(default='default_mebel.jpg', upload_to='', verbose_name='Эскиз4')),
                ('order_3D_model', models.ImageField(default='default_mebel.jpg', upload_to='', verbose_name='3D модель')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ф.И.О.')),
            ],
        ),
    ]
