# Generated by Django 5.0.6 on 2024-06-15 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('1', 'Гардероб'), ('2', 'Детская'), ('3', 'Комод'), ('4', 'Кухня'), ('5', 'Прихожая')], default='1', max_length=1, verbose_name='Тип мебели')),
                ('form', models.CharField(choices=[('1', 'Прямая'), ('2', 'Г-образная'), ('3', 'П-образная'), ('4', 'С барной стойкой'), ('5', 'С островом')], default='1', max_length=1, verbose_name='Форма мебели')),
                ('body_material', models.CharField(choices=[('1', 'ЛДСП'), ('2', 'МДФ'), ('3', 'Пленка ПВХ'), ('4', 'Пластик AGT'), ('5', 'Пластик Fenix'), ('6', 'Эмаль')], default='1', max_length=1, verbose_name='Материал корпуса')),
                ('facades_material', models.CharField(choices=[('1', 'ЛДСП'), ('2', 'МДФ'), ('3', 'Пленка ПВХ'), ('4', 'Пластик AGT'), ('5', 'Пластик Fenix'), ('6', 'Эмаль')], default='1', max_length=1, verbose_name='Материал фасадов')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 4')),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ф.И.О.'),
        ),
    ]
