# Generated by Django 5.0.6 on 2024-06-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loyalty',
        ),
    ]
