# Generated by Django 5.0.6 on 2024-06-22 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0002_delete_loyalty'),
        ('users', '0002_loyalty_remove_profile_loyalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_by_loyalty_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.loyalty'),
        ),
    ]
