# Generated by Django 5.0.6 on 2024-06-23 11:36

import birthday.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyalty',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('survey_repair', models.CharField(choices=[('0', 'Нет, не планирую'), ('1', 'Планирую, но не определился со временем'), ('2', 'Уже идет'), ('3', 'Скоро приступаем'), ('4', 'В течение полугода'), ('5', 'В течение года')], default='0', max_length=1, verbose_name='Планируете ли вы ремонт')),
                ('survey_children', models.BooleanField(default=False, verbose_name='Есть ли у вас дети')),
                ('bonus', models.CharField(choices=[('1', 'Скидка 10%\nДополнительная скидка при оплате техники или сантехники'), ('2', 'Скидка на столешницы SLOTEX\nСтолешница Slotex - это влагостойкая ДСП, облицованная декоративным покрытием Slotex.'), ('3', 'Дополнительная скидка 5%\nИспользуйте дополнительную скидку для оплаты всего заказа.\nНе включает в себя стоимость доставки и сборки'), ('4', '10 000 рублей\nДенежными средствами (не на бонусный счёт)'), ('5', '15 000 рублей\nНа бонусный счёт (1 бонус = 1 рубль)'), ('6', '20 000 рублей\nМебель стоимость до 20 000 рублей в подарок')], default='1', max_length=1, verbose_name='Планируете ли вы ремонт')),
                ('card_number', models.CharField(max_length=19, verbose_name='Номер карты')),
                ('loyalty_url', models.URLField(blank=True, verbose_name='Ссылка для друга')),
                ('loyalty_code', models.CharField(max_length=20, verbose_name='Код программы лояльности')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('surname', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User джанго модели')),
                ('birth_date_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('birth_date', birthday.fields.BirthdayField(null=True, verbose_name='Дата рождения')),
                ('mailing', models.BooleanField(blank=True, default=False, verbose_name='Согласие на рассылку')),
                ('personal_data_processing', models.BooleanField(blank=True, default=False, verbose_name='Согласие на обработку персональных данных')),
            ],
        ),
    ]
