# Generated by Django 5.0.6 on 2024-06-21 19:08

import birthday.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('surname', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User джанго модели')),
                ('birth_date_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('birth_date', birthday.fields.BirthdayField(null=True, verbose_name='Дата рождения')),
                ('mailing', models.BooleanField(blank=True, default=False, verbose_name='Согласие на рассылку')),
                ('personal_data_processing', models.BooleanField(blank=True, default=False, verbose_name='Согласие на обработку персональных данных')),
                ('loyalty', models.URLField(default=None, null=True, verbose_name='Код программы лояльности')),
            ],
        ),
    ]
