# Generated by Django 5.0.6 on 2024-06-04 19:49

import birthday.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=birthday.fields.BirthdayField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bonus_balance',
            field=models.IntegerField(blank=True, null=True, verbose_name=' Текущий баланс бонусных баллов'),
        ),
        migrations.AddField(
            model_name='profile',
            name='children_having',
            field=models.CharField(choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=3, null=True, verbose_name='Наличие детей'),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=models.CharField(max_length=150, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')], verbose_name='Телефон'),
        ),
    ]
