# Generated by Django 5.0.6 on 2024-06-09 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='mailing',
            field=models.BooleanField(default=False, verbose_name='Согласие на рассылку'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mebel_type',
            field=models.CharField(max_length=250, null=True, verbose_name='Тип мебели'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_data_processing',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='profile',
            name='repair_planing',
            field=models.BooleanField(default=False, verbose_name='Планирование ремонта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='repair_planing_time',
            field=models.CharField(max_length=50, null=True, verbose_name='Когда планируется ремонт?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='children_having',
            field=models.BooleanField(default=False, verbose_name='Наличие детей'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть указан в формате: '+7ХХХХХХХХХХ'. Максимум 12 символов.", regex='^\\+?1?\\d{9,12}$')], verbose_name='Телефон'),
        ),
    ]
