# Generated by Django 5.0.6 on 2024-07-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='bonus',
            field=models.CharField(blank=True, choices=[('1', 'Скидка 10%\nДополнительная скидка при оплате техники или сантехники'), ('2', 'Скидка на столешницы SLOTEX\nСтолешница Slotex - это влагостойкая ДСП, облицованная декоративным покрытием Slotex.'), ('3', 'Дополнительная скидка 5%\nИспользуйте дополнительную скидку для оплаты всего заказа.\nНе включает в себя стоимость доставки и сборки'), ('4', '10 000 рублей\nДенежными средствами (не на бонусный счёт)'), ('5', '15 000 рублей\nНа бонусный счёт (1 бонус = 1 рубль)'), ('6', '20 000 рублей\nМебель стоимость до 20 000 рублей в подарок')], default='1', max_length=1, verbose_name='Планируете ли вы ремонт'),
        ),
    ]
