# Generated by Django 5.0.6 on 2024-06-12 17:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_repair_planing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='furniture_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'Кухня'), ('2', 'Гардероб'), ('3', 'Прихожая'), ('4', 'Стелаж'), ('5', 'Комод')], max_length=1), size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='repair_planing_time',
            field=models.CharField(choices=[('0', 'Нет, не планирую'), ('1', 'Планирую, но не определился со временем'), ('2', 'Уже идет'), ('3', 'Скоро приступаем'), ('4', 'В течение полугода'), ('5', 'В течение года')], max_length=1, null=True, verbose_name='Когда планируется ремонт?'),
        ),
    ]
