# Generated by Django 5.0.6 on 2024-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_repair_planing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(null=True, verbose_name='Ф.И.О.'),
        ),
    ]
