# Generated by Django 5.0.6 on 2024-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_phone_alter_profile_furniture_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='furniture_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.AddField(
            model_name='profile',
            name='f_dresser',
            field=models.BooleanField(blank=True, default=False, verbose_name='Комод'),
        ),
        migrations.AddField(
            model_name='profile',
            name='f_hallway',
            field=models.BooleanField(blank=True, default=False, verbose_name='Прихожая'),
        ),
        migrations.AddField(
            model_name='profile',
            name='f_kitchen',
            field=models.BooleanField(blank=True, default=False, verbose_name='Кухня'),
        ),
        migrations.AddField(
            model_name='profile',
            name='f_rack',
            field=models.BooleanField(blank=True, default=False, verbose_name='Стеллаж'),
        ),
        migrations.AddField(
            model_name='profile',
            name='f_wardrobe',
            field=models.BooleanField(blank=True, default=False, verbose_name='Гардероб'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_nane',
            field=models.CharField(default='K K K', verbose_name='Ф.И.О.'),
            preserve_default=False,
        ),
    ]
