# Generated by Django 5.0.6 on 2024-06-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_furniture_type_remove_profile_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_nane',
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, verbose_name='Отчество'),
        ),
    ]
