# Generated by Django 5.0.6 on 2024-06-10 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='children_having',
            field=models.BooleanField(blank=True, default=False, verbose_name='Наличие детей'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mailing',
            field=models.BooleanField(blank=True, default=False, verbose_name='Согласие на рассылку'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User джанго модели'),
        ),
    ]
