# Generated by Django 5.0.6 on 2024-06-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_full_nane_profile_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='f_dresser',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='f_hallway',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='f_kitchen',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='f_rack',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='f_wardrobe',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='repair_planing_time',
        ),
    ]
