# Generated by Django 5.0.6 on 2024-06-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_children_having_alter_profile_mailing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_data_processing',
            field=models.BooleanField(blank=True, default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
