# Generated by Django 5.0.6 on 2024-06-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_full_name_profile_surname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mebel_type',
            new_name='furniture_type',
        ),
    ]
