# Generated by Django 5.0.6 on 2024-06-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_f_dresser_remove_profile_f_hallway_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='children_having',
        ),
    ]
