# Generated by Django 5.0.6 on 2024-06-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_mebel_type_profile_furniture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='furniture_type',
            field=models.CharField(choices=[('1', 'Кухня'), ('2', 'Гардероб'), ('3', 'Прихожая'), ('4', 'Стелаж'), ('5', 'Комод')], max_length=250, null=True, verbose_name='Тип мебели'),
        ),
    ]
